name: Build and test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get install -y libgmp-dev shellcheck

      - name: Lint shell scripts
        run: |
          echo "Linting shell scripts..."
          find . -type f -name "*.sh" | xargs shellcheck -S warning
          if [ $? -ne 0 ]; then
            echo "Shell script linting failed"
            exit 1
          fi

      - name: Build
        run: gcc -o fib fib.c -lgmp

      - name: Test
        run: |
          chmod +x test.sh
          ./test.sh
