name: Build and test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint:
    uses: ./.github/workflows/linter.yml

  build:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get install -y libgmp-dev

      - name: Build
        run: gcc -o fib fib.c -lgmp

      - name: Test
        run: |
          chmod +x test.sh
          ./test.sh
