name: Build and test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v3

      - name: Create file hash
        id: files-hash
        run: |
          SHELL_HASH=$(find . -name "*.sh" -type f -exec sha256sum {} \; | sort | sha256sum | cut -d' ' -f1)
          C_HASH=$(find . -name "*.c" -o -name "*.h" -type f -exec sha256sum {} \; | sort | sha256sum | cut -d' ' -f1)
          echo "shell_hash=$SHELL_HASH" >> $GITHUB_OUTPUT
          echo "c_hash=$C_HASH" >> $GITHUB_OUTPUT

      - name: Configure shellcheck cache
        uses: actions/cache@v3
        id: cache-shellcheck
        with:
          path: |
            ~/.local/bin/shellcheck
            ~/.cabal/bin/shellcheck
          key: ${{ runner.os }}-shellcheck-${{ steps.files-hash.outputs.shell_hash }}
          restore-keys: |
            ${{ runner.os }}-shellcheck-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck clang-format cppcheck

      - name: Run lint script
        run: |
          chmod +x tests/lint.sh
          cd tests && ./lint.sh

  build:
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgmp-dev

      - name: Build with Makefile
        run: make

      - name: Test
        run: |
          chmod +x tests/build.sh
          cd tests && ./build.sh

  build-macos:
    needs: lint
    runs-on: macos-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: brew install gmp

      - name: Build with Makefile
        run: make

      - name: Test
        run: |
          chmod +x tests/build.sh
          cd tests && ./build.sh
